import { loomBuild } from "../../tsdown.base.ts";

export default loomBuild({
	// `pkg/` is wasm-pack output, generated by `pnpm build:native` and shipped
	// verbatim. Keep the glue external so dist/index.js still reaches it at
	// `../pkg/…` — the same relative hop that works from src/ in the workspace.
	deps: { neverBundle: [/^\.\.\/pkg\//] },
});
